import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";

import {
    NavbarSection,
    MountingWrapper
} from "@/components"

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            <link rel="icon" href="/favicon.png" sizes="any"/>
        </head>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >

        <div className="relative min-h-screen bg-gray-900 text-white overflow-x-hidden">
            <div className="relative z-10">
                <MountingWrapper>
                    <div className="relative min-h-screen bg-gray-900 text-white overflow-x-hidden">
                        {children}
                    </div>

                </MountingWrapper>
            </div>
        </div>
        </body>
        </html>
    );
}
